version: '3.4'

services:
    
  rabbitmq:
    image: rabbitmq:3-management
  
  ecommerceorderdb:
    image: mcr.microsoft.com/mssql/server

  ecommerceproductdb:
    image: mongo

  ecommercebasketdb:
    image: redis

  ecommerce.product.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductapi
    build:
      context: .
      dockerfile: src/Services/Product/ECommerce.Product.API/Dockerfile

  ecommerce.apigateway:
    image: ${DOCKER_REGISTRY-}ecommerceapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/ECommerce.APIGateway/Dockerfile

  ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}ecommercebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/ECommerce.Basket.API/Dockerfile


  ecommerce.ordering.api:
    image: ${DOCKER_REGISTRY-}ecommerceorderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/ECommerce.Ordering.API/Dockerfile

