version: '3.4'

services:

  ecommercemongodb:
    image: mongo

  ecommerce.product.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductapi
    build:
      context: .
      dockerfile: src/Services/Product/ECommerce.Product.API/Dockerfile

  ecommerce.apigateway:
    image: ${DOCKER_REGISTRY-}ecommerceapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/ECommerce.APIGateway/Dockerfile

  ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}ecommercebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/ECommerce.Basket.API/Dockerfile

